local _, A = ...








A.artSlots = {
    bar04 = "bar04",
    compassDivider = "compass-divider",
    compassTileCut = "compass-tile-cut",
    compassTileNotch = "compass-tile-notch",
    compassTilePipBL = "compass-tile-pip-bl",
    compassTilePipTL = "compass-tile-pip-tl",
    crest = "crest-art",
    kbFade = "kb-fade",
    kbTileFace = "kb-tile-face",
    kbTileSocket = "kb-tile-socket",
    mapEdge = "map-edge",
    mapHalo = "map-halo",
    mapMin = "map-min",
    mapScrim = "map-scrim",
    oakBumper = "oak-bumper",
    oakBumperGlow = "oak-bumper-glow",
    oakBumperShadow = "oak-bumper-shadow",
    oakChip = "oak-chip",
    oakChipClear = "oak-chip-clear",
    oakChipDebris = "oak-chip-debris",
    oakChipHead = "oak-chip-head",
    oakChipMask = "oak-chip-mask",
    oakChipReveal = "oak-chip-reveal",
    oakChipRim = "oak-chip-rim",
    oakCompassTile = "oak-compass-tile",
    oakDivider = "oak-divider",
    oakDividerShadow = "oak-divider-shadow",
    oakKbFace = "oak-kb-face",
    oakKbSocket = "oak-kb-socket",
    oakKnot = "oak-knot",
    oakMapMantle = "oak-map-mantle",
    oakPlate2Cap = "oak-plate2-cap",
    oakPlate2Lum = "oak-plate2-lum",
    oakPlate2Plain = "oak-plate2-plain",
    oakPlate2Shade = "oak-plate2-shade",
    oakPlate3Cap = "oak-plate3-cap",
    oakPlate3Lum = "oak-plate3-lum",
    oakPlate3Plain = "oak-plate3-plain",
    oakPlate3Shade = "oak-plate3-shade",
    oakPlateCap = "oak-plate-cap",
    oakPlateLum = "oak-plate-lum",
    oakPlatePlain = "oak-plate-plain",
    oakPlateShade = "oak-plate-shade",
    oakRail = "oak-rail",
    oakSmallCap = "oak-small-cap",
    oakSmallLum = "oak-small-lum",
    oakSmallPlain = "oak-small-plain",
    oakSmallShade = "oak-small-shade",
    oakStud = "oak-stud",
    oakTile = "oak-tile",
    oakTilePip = "oak-tile-pip",
    oakWindowBranch = "oak-window-branch",
    obsidian = "obsidian",
    optionsBg = "options-bg",
    plate02InlayCap = "plate02-inlay-cap",
    plate02InlayLum = "plate02-inlay-lum",
    plate02Plain = "plate02-plain",
    rblb = "rblb",
    rblbGlow = "rblb-glow",
    rise = "rise",
    riseWide = "rise-wide",
    ["tile-notch-cap"] = "tile-notch-cap",
    ["tile-notch-lum"] = "tile-notch-lum",
    ["tile-pip-cap"] = "tile-pip-cap",
    ["tile-pip-lum"] = "tile-pip-lum",
    ["tile-pipnotch-cap"] = "tile-pipnotch-cap",
    ["tile-pipnotch-lum"] = "tile-pipnotch-lum",
    ["tile-pipnotchr-cap"] = "tile-pipnotchr-cap",
    ["tile-pipnotchr-lum"] = "tile-pipnotchr-lum",
    ["tile-plain-cap"] = "tile-plain-cap",
    ["tile-plain-lum"] = "tile-plain-lum",
    tilePlain = "tile-plain",
}









A.artLayers = {
    ["bar04"] = { body = "bar04-body", acc = "bar04-acc" },
    ["chrome-seat"] = { mat = "chrome-seat-mat" },
    ["compass-divider"] = { mat = "compass-divider-mat", acc = "compass-divider-acc" },
    ["compass-tile-cut"] = { mat = "compass-tile-cut-mat" },
    ["compass-tile-notch"] = { mat = "compass-tile-notch-mat" },
    ["compass-tile-pip-bl"] = { mat = "compass-tile-pip-bl-mat", acc = "compass-tile-pip-bl-acc" },
    ["compass-tile-pip-tl"] = { mat = "compass-tile-pip-tl-mat", acc = "compass-tile-pip-tl-acc" },
    ["kb-plinth"] = { mat = "kb-plinth-mat" },
    ["kb-tile-face"] = { mat = "kb-tile-face-mat", acc = "kb-tile-face-acc" },
    ["kb-tile-socket"] = { mat = "kb-tile-socket-mat", acc = "kb-tile-socket-acc" },
    ["map-min"] = { body = "map-min-body", acc = "map-min-acc" },
    ["oak-bumper"] = { body = "oak-bumper-body", acc = "oak-bumper-acc" },
    ["oak-compass-tile"] = { body = "oak-compass-tile-body", acc = "oak-compass-tile-acc" },
    ["oak-divider"] = { body = "oak-divider-body", acc = "oak-divider-acc" },
    ["oak-kb-face"] = { body = "oak-kb-face-body", acc = "oak-kb-face-acc" },
    ["oak-kb-socket"] = { body = "oak-kb-socket-body", acc = "oak-kb-socket-acc" },
    ["oak-map-mantle"] = { body = "oak-map-mantle-body", acc = "oak-map-mantle-acc" },
    ["oak-plate-cap"] = { body = "oak-plate-cap-body", acc = "oak-plate-cap-acc" },
    ["oak-plate-plain"] = { body = "oak-plate-plain-body", acc = "oak-plate-plain-acc" },
    ["oak-plate2-cap"] = { body = "oak-plate2-cap-body", acc = "oak-plate2-cap-acc" },
    ["oak-plate2-plain"] = { body = "oak-plate2-plain-body", acc = "oak-plate2-plain-acc" },
    ["oak-plate3-cap"] = { body = "oak-plate3-cap-body", acc = "oak-plate3-cap-acc" },
    ["oak-plate3-plain"] = { body = "oak-plate3-plain-body", acc = "oak-plate3-plain-acc" },
    ["oak-rail"] = { body = "oak-rail-body", acc = "oak-rail-acc" },
    ["oak-small-cap"] = { body = "oak-small-cap-body", acc = "oak-small-cap-acc" },
    ["oak-small-plain"] = { body = "oak-small-plain-body", acc = "oak-small-plain-acc" },
    ["oak-tile"] = { body = "oak-tile-body", acc = "oak-tile-acc" },
    ["oak-tile-pip"] = { body = "oak-tile-pip-body", acc = "oak-tile-pip-acc" },
    ["oak-window-branch"] = { body = "oak-window-branch-body", acc = "oak-window-branch-acc" },
    ["options-bg"] = { body = "options-bg-body", acc = "options-bg-acc" },
    ["plate02-plain"] = { mat = "plate02-plain-mat", acc = "plate02-plain-acc" },
    ["rblb"] = { body = "rblb-body", acc = "rblb-acc" },
    ["socket-glyph"] = { body = "socket-glyph-body", acc = "socket-glyph-acc" },
    ["socket-glyph-face"] = { body = "socket-glyph-face-body", acc = "socket-glyph-face-acc" },
    ["socket-plinth"] = { mat = "socket-plinth-mat", acc = "socket-plinth-acc" },
    ["tile-pip-cap"] = { body = "tile-pip-cap-body", acc = "tile-pip-cap-acc" },
    ["tile-pipnotch-cap"] = { body = "tile-pipnotch-cap-body", acc = "tile-pipnotch-cap-acc" },
    ["tile-pipnotchr-cap"] = { body = "tile-pipnotchr-cap-body", acc = "tile-pipnotchr-cap-acc" },
}
