local _, A = ...








A.artSlots = {
    banner = "dusk-banner",
    bar04 = "bar04",
    bar06 = "bar06",
    barLedge = "bar-ledge",
    barPlate = "bar-plate",
    barRail = "bar-rail",
    barRailV = "bar-rail-v",
    compassDivider = "compass-divider",
    compassTileCut = "compass-tile-cut",
    compassTileNotch = "compass-tile-notch",
    compassTilePipBL = "compass-tile-pip-bl",
    compassTilePipTL = "compass-tile-pip-tl",
    crest = "crest-art",
    kbFade = "kb-fade",
    kbTile = "kb-tile",
    kbTileFace = "kb-tile-face",
    kbTileSocket = "kb-tile-socket",
    mapBg = "map-bg",
    mapEdge = "map-edge",
    mapFade = "map-fade",
    mapHalo = "map-halo",
    mapMin = "map-min",
    obsidian = "obsidian",
    optionsBg = "options-bg",
    plate02 = "plate02",
    plate02Fill = "plate02-fill",
    plate02InlayCap = "plate02-inlay-cap",
    plate02InlayLum = "plate02-inlay-lum",
    plate02Plain = "plate02-plain",
    rail03 = "rail03",
    rblb = "rblb",
    rblbGlow = "rblb-glow",
    rise = "rise",
    riseWide = "rise-wide",
    ["sigil-diamond"] = "sigil-diamond-art",
    ["sigil-drop"] = "sigil-drop-art",
    ["sigil-leaf"] = "sigil-leaf-art",
    ["sigil-moon"] = "sigil-moon-art",
    ["sigil-seed"] = "sigil-seed-art",
    ["sigil-spiral"] = "sigil-spiral-art",
    ["sigil-sun"] = "sigil-sun-art",
    slab02 = "slab02",
    ["tile-notch-cap"] = "tile-notch-cap",
    ["tile-notch-lum"] = "tile-notch-lum",
    ["tile-pip-cap"] = "tile-pip-cap",
    ["tile-pip-lum"] = "tile-pip-lum",
    ["tile-pipnotch-cap"] = "tile-pipnotch-cap",
    ["tile-pipnotch-lum"] = "tile-pipnotch-lum",
    ["tile-pipnotchr-cap"] = "tile-pipnotchr-cap",
    ["tile-pipnotchr-lum"] = "tile-pipnotchr-lum",
    ["tile-plain-cap"] = "tile-plain-cap",
    ["tile-plain-lum"] = "tile-plain-lum",
    tilePlain = "tile-plain",
}









A.artLayers = {
    ["bar-ledge"] = { mat = "bar-ledge-mat", acc = "bar-ledge-acc" },
    ["bar-plate"] = { mat = "bar-plate-mat", acc = "bar-plate-acc" },
    ["bar-rail"] = { mat = "bar-rail-mat", acc = "bar-rail-acc" },
    ["bar-rail-v"] = { mat = "bar-rail-v-mat" },
    ["bar04"] = { body = "bar04-body", acc = "bar04-acc" },
    ["bar06"] = { body = "bar06-body", acc = "bar06-acc" },
    ["chrome-seat"] = { mat = "chrome-seat-mat" },
    ["compass-divider"] = { mat = "compass-divider-mat", acc = "compass-divider-acc" },
    ["compass-slab"] = { mat = "compass-slab-mat" },
    ["compass-slot"] = { mat = "compass-slot-mat", acc = "compass-slot-acc" },
    ["compass-slot-brass"] = { mat = "compass-slot-brass-mat", acc = "compass-slot-brass-acc" },
    ["compass-slot-brass-socket"] = { mat = "compass-slot-brass-socket-mat", acc = "compass-slot-brass-socket-acc" },
    ["compass-slot-socket"] = { mat = "compass-slot-socket-mat", acc = "compass-slot-socket-acc" },
    ["compass-tile-cut"] = { mat = "compass-tile-cut-mat" },
    ["compass-tile-notch"] = { mat = "compass-tile-notch-mat" },
    ["compass-tile-pip-bl"] = { mat = "compass-tile-pip-bl-mat", acc = "compass-tile-pip-bl-acc" },
    ["compass-tile-pip-tl"] = { mat = "compass-tile-pip-tl-mat", acc = "compass-tile-pip-tl-acc" },
    ["kb-floor"] = { mat = "kb-floor-mat" },
    ["kb-page"] = { body = "kb-page-body", acc = "kb-page-acc" },
    ["kb-plinth"] = { mat = "kb-plinth-mat" },
    ["kb-slot"] = { mat = "kb-slot-mat", acc = "kb-slot-acc" },
    ["kb-slot-brass"] = { mat = "kb-slot-brass-mat", acc = "kb-slot-brass-acc" },
    ["kb-slot-brass-socket"] = { mat = "kb-slot-brass-socket-mat", acc = "kb-slot-brass-socket-acc" },
    ["kb-slot-socket"] = { mat = "kb-slot-socket-mat", acc = "kb-slot-socket-acc" },
    ["kb-tile"] = { mat = "kb-tile-mat", acc = "kb-tile-acc" },
    ["kb-tile-face"] = { mat = "kb-tile-face-mat", acc = "kb-tile-face-acc" },
    ["kb-tile-socket"] = { mat = "kb-tile-socket-mat", acc = "kb-tile-socket-acc" },
    ["map-bg"] = { body = "map-bg-body", acc = "map-bg-acc" },
    ["map-min"] = { body = "map-min-body", acc = "map-min-acc" },
    ["options-bg"] = { body = "options-bg-body", acc = "options-bg-acc" },
    ["plate02"] = { mat = "plate02-mat", acc = "plate02-acc" },
    ["plate02-plain"] = { mat = "plate02-plain-mat", acc = "plate02-plain-acc" },
    ["rail03"] = { mat = "rail03-mat", acc = "rail03-acc" },
    ["rblb"] = { body = "rblb-body", acc = "rblb-acc" },
    ["slab02"] = { mat = "slab02-mat", acc = "slab02-acc" },
    ["socket-facet"] = { mat = "socket-facet-mat", acc = "socket-facet-acc" },
    ["socket-glyph"] = { body = "socket-glyph-body", acc = "socket-glyph-acc" },
    ["socket-glyph-face"] = { body = "socket-glyph-face-body", acc = "socket-glyph-face-acc" },
    ["socket-ground"] = { mat = "socket-ground-mat" },
    ["socket-plinth"] = { mat = "socket-plinth-mat", acc = "socket-plinth-acc" },
    ["socket-tab"] = { mat = "socket-tab-mat", acc = "socket-tab-acc" },
    ["tile-pip-cap"] = { body = "tile-pip-cap-body", acc = "tile-pip-cap-acc" },
    ["tile-pipnotch-cap"] = { body = "tile-pipnotch-cap-body", acc = "tile-pipnotch-cap-acc" },
    ["tile-pipnotchr-cap"] = { body = "tile-pipnotchr-cap-body", acc = "tile-pipnotchr-cap-acc" },
}
